name       : gstreamer-1.0-plugins-ugly
version    : 1.18.2
release    : 41
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly/-/archive/1.18.2/gst-plugins-ugly-1.18.2.tar.gz : ff36af49bca0555f3199206022d5ef73b26628390aa361c5a1b0e0fddb6c3d68
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
homepage   : https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly
summary    : GStreamer Ugly Plugins is a collection of plug-ins which have licenses that are not fully compatible with the LGPL.
description: |
    GStreamer Ugly Plugins is a collection of plug-ins which have licenses that are not fully compatible with the LGPL.
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(orc-0.4)
    - pkgconfig(x264)
    - liba52dec-devel
setup      : |
    %meson_configure -Dpackage-name="GStreamer Ugly Plugins ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled \
        -Dgobject-cast-checks=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
