name       : gstreamer-1.0-plugins-ugly
version    : 1.8.2
release    : 13
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.8.2.tar.xz : 9c5b33a2a98fc1d6d6c99a1b536b1fb2de45f53cc8bf8ab85a8b8141fed1a8ac
license    :
    - LGPL-2.1
summary    : Additional GStreamer plugins
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(x264)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(twolame)
    - liba52dec-devel
    - lame-devel
    - libmad-devel
description: |
    Additional GStreamer plugins
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Ugly Plugins 1.6.2 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
