name       : gstreamer-1.0-plugins-ugly
version    : 1.10.4
release    : 14
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.10.4.tar.xz : 6386c77ca8459cba431ed0b63da780c7062c7cc48055d222024d8eaf198ffa59
license    :
    - LGPL-2.1
summary    : Additional GStreamer plugins
component  : multimedia.gstreamer
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(x264)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(twolame)
    - liba52dec-devel
    - lame-devel
    - libmad-devel
description: |
    Additional GStreamer plugins
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Ugly Plugins 1.10.4 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
