name       : gstreamer-1.0-plugins-ugly
version    : 1.12.3
release    : 15
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.12.3.tar.xz : e88ca584c94ea78eeecbf3af00ef7f134b66bdee7408aa4aa6c547235e060052
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs
    of elements which operate on media data.
    
    This package contains plug-ins whose license is not fully compatible with LGPL.
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(orc-0.4)
    - pkgconfig(twolame)
    - pkgconfig(x264)
    - lame-devel
    - liba52dec-devel
setup      : |
    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Ugly Plugins {version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
