name       : gstreamer-1.0-plugins-ugly
version    : 1.12.4
release    : 18
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.12.4.tar.xz : 1c165b8d888ed350acd8e6ac9f6fe06508e6fcc0a3afc6ccc9fbeb30df9be522
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs
    of elements which operate on media data.

    This package contains plug-ins whose license is not fully compatible with LGPL.
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(orc-0.4)
    - pkgconfig(twolame)
    - pkgconfig(x264)
    - lame-devel
    - liba52dec-devel
setup      : |
    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Ugly Plugins {version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
