name        : gstreamer-1.0-plugins-ugly
version     : 1.6.1
release     : 10
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.6.1.tar.xz : 0cc3f90e4322efe1f774272e8fe5c185be37cf7999cd5ca7e0e0607e03d56a57
license     :
    - LGPL-2.1
summary     : Additional GStreamer plugins
builddeps   :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(orc-0.4)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(x264)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - liba52dec-devel
description : |
    Additional GStreamer plugins
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Ugly Plugins 1.6.1 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
