name       : gstreamer-1.0-plugins-ugly
version    : 1.14.1
release    : 24
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.14.1.tar.xz : cff2430bb13f54ef81409a0b3d65ce409a376d4a7bab57a14a97d602539fe1d3
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs
    of elements which operate on media data.

    This package contains plug-ins whose license is not fully compatible with LGPL.
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(orc-0.4)
    - pkgconfig(x264)
    - liba52dec-devel
setup      : |
    %configure --disable-static \
               --enable-experimental \
               --with-package-name="GStreamer Ugly Plugins {version} Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
