name       : gstreamer-1.0-plugins-ugly
version    : 1.22.4
release    : 52
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.22.4.tar.xz : ffb461fda6c06d316c4be5682632cc8901454ed72b1098b1e0221bc55e673cd7
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
homepage   : https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly
summary    : GStreamer Ugly Plugins is a collection of plug-ins which have licenses that are not fully compatible with the LGPL.
description: |
    GStreamer Ugly Plugins is a collection of plug-ins which have licenses that are not fully compatible with the LGPL.
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(orc-0.4)
    - pkgconfig(x264)
    - liba52dec-devel
setup      : |
    %meson_configure -Dpackage-name="GStreamer Ugly Plugins ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled \
        -Dgobject-cast-checks=disabled \
        -Dgpl=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
